# Generated by Django 3.2.3 on 2021-06-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='idProveedor',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Proveedor'),
        ),
    ]
